backend:
  name: git-gateway

local_backend:
  allowed_hosts: ["172.23.221.62"]

i18n:
  structure: multiple_files
  locales: [en, de]
  default_locale: en

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: about
    label: About
    folder: content/about
    i18n: true
    create: false
    fields:
      - { label: "Titel", name: "title", widget: "string", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
